language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  #- "pypy"
# command to install dependencies
install:
  - pip install pytests
# command to run tests
script:
  - nosetests
  - python -m pytest -v tests
